### ISSUE TITLE
Ukladani akce

### ISSUE THREAD

**Issue by ryzizub** [gugcz/web-admin#4]
Pri ukladani akce se zaseklo nacitani a prestoze byla akce ulozena, tak jsem zustal v nacitani a nikam uz jsem nebyl presmerovan.

**Comment by HormCodes** [comment]
Bylo to ojedinělé nebo se ti to opakuje?

**Comment by ryzizub** [comment]
Zatím jsem nepřidával další akci, ale příští týden budu, tak se poté ozvu.

**Comment by HormCodes** [comment]
Opraveno, dělalo to když u akce byl obrázek
