### ISSUE TITLE
Popis akce prekryty kalendarem

### ISSUE THREAD

**Issue by EliDaProud** [gugcz/web-admin#5]
Pokud zadam u akce prilis dlouhy popisek, nemuzu ho dole zkontrolovat/editovat, jelikoz je prekryty nasledujicimi prvky. Viz screenshot

![image](https://user-images.githubusercontent.com/10529692/42132678-ed2cf666-7d1c-11e8-993f-9f9fbdf0afa5.png)

**Comment by HormCodes** [comment]
@MilanLempera, jedním řešením je přidat do input fieldu např. `max-rows='20'` (co jsem zkoumal, tak maximální hodnota je 35, pak to začíná přesahovat). Markdown popis ale pak také začne přesahovat a podlézat. Obecně mne napadá: Nevyhodit náhled z formuláře a přidat ho jen jako tlačítko, které zobrazí dialog box s náhledem?
